/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /root/catkin_ws/src/openreroc_posturesensor/msg/accel_angle.msg
 *
 */


#ifndef OPENREROC_POSTURESENSOR_MESSAGE_ACCEL_ANGLE_H
#define OPENREROC_POSTURESENSOR_MESSAGE_ACCEL_ANGLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace openreroc_posturesensor
{
template <class ContainerAllocator>
struct accel_angle_
{
  typedef accel_angle_<ContainerAllocator> Type;

  accel_angle_()
    : ac_x_ang(0.0)
    , ac_y_ang(0.0)
    , ac_z_ang(0.0)  {
    }
  accel_angle_(const ContainerAllocator& _alloc)
    : ac_x_ang(0.0)
    , ac_y_ang(0.0)
    , ac_z_ang(0.0)  {
    }



   typedef float _ac_x_ang_type;
  _ac_x_ang_type ac_x_ang;

   typedef float _ac_y_ang_type;
  _ac_y_ang_type ac_y_ang;

   typedef float _ac_z_ang_type;
  _ac_z_ang_type ac_z_ang;




  typedef boost::shared_ptr< ::openreroc_posturesensor::accel_angle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::openreroc_posturesensor::accel_angle_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct accel_angle_

typedef ::openreroc_posturesensor::accel_angle_<std::allocator<void> > accel_angle;

typedef boost::shared_ptr< ::openreroc_posturesensor::accel_angle > accel_anglePtr;
typedef boost::shared_ptr< ::openreroc_posturesensor::accel_angle const> accel_angleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::openreroc_posturesensor::accel_angle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::openreroc_posturesensor::accel_angle_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace openreroc_posturesensor

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'openreroc_posturesensor': ['/root/catkin_ws/src/openreroc_posturesensor/msg'], 'std_msgs': ['/opt/ros/groovy/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::openreroc_posturesensor::accel_angle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openreroc_posturesensor::accel_angle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openreroc_posturesensor::accel_angle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openreroc_posturesensor::accel_angle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openreroc_posturesensor::accel_angle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openreroc_posturesensor::accel_angle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::openreroc_posturesensor::accel_angle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6047597fababcf33c4e34194ab8dba93";
  }

  static const char* value(const ::openreroc_posturesensor::accel_angle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6047597fababcf33ULL;
  static const uint64_t static_value2 = 0xc4e34194ab8dba93ULL;
};

template<class ContainerAllocator>
struct DataType< ::openreroc_posturesensor::accel_angle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "openreroc_posturesensor/accel_angle";
  }

  static const char* value(const ::openreroc_posturesensor::accel_angle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::openreroc_posturesensor::accel_angle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 ac_x_ang\n\
float32 ac_y_ang\n\
float32 ac_z_ang\n\
\n\
";
  }

  static const char* value(const ::openreroc_posturesensor::accel_angle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::openreroc_posturesensor::accel_angle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ac_x_ang);
      stream.next(m.ac_y_ang);
      stream.next(m.ac_z_ang);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct accel_angle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::openreroc_posturesensor::accel_angle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::openreroc_posturesensor::accel_angle_<ContainerAllocator>& v)
  {
    s << indent << "ac_x_ang: ";
    Printer<float>::stream(s, indent + "  ", v.ac_x_ang);
    s << indent << "ac_y_ang: ";
    Printer<float>::stream(s, indent + "  ", v.ac_y_ang);
    s << indent << "ac_z_ang: ";
    Printer<float>::stream(s, indent + "  ", v.ac_z_ang);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENREROC_POSTURESENSOR_MESSAGE_ACCEL_ANGLE_H
